CREATE TABLE IF NOT EXISTS `colors` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `host` VARCHAR(150) NOT NULL,
    `color1` VARCHAR(5) NOT NULL,
    `color2` VARCHAR(5) NOT NULL,
    `inserted_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = InnoDB AUTO_INCREMENT = 384 DEFAULT CHARSET = utf8mb3;